bg = "#2d353b"
bg_alt = "#232a2e"
fg = "#d3c6aa"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
purple = "#d699b6"
cyan = "#83c092"
accent = "#7fbbb3"
dunst_bg = "#2d353b"
dunst_fg = "#d3c6aa"
ok = "#a7c080"
bg_crit = "#3d1f22"
fg_crit = "#ffdada"
gtk_theme = "Sweet-Dark"
gtk_icon = "Papirus-Dark"
icon_color = "green"
