bg = "#282828"
bg_alt = "#1d2021"
fg = "#ebdbb2"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
purple = "#d3869b"
cyan = "#8ec07c"
accent = "#fabd2f"
dunst_bg = "#282828"
dunst_fg = "#ebdbb2"
ok = "#b8bb26"
bg_crit = "#3c1f1c"
fg_crit = "#ffdada"
gtk_theme = "Sweet-Dark"
gtk_icon = "Papirus-Dark"
icon_color = "yellow"
