background            #1f2430
foreground            #cbccc6
selection_foreground  #1f2430
selection_background  #5ccfe6

color0  #171b24
color1  #ff6666
color2  #bae67e
color3  #ffcc66
color4  #5ccfe6
color5  #c3a6ff
color6  #95e6cb
color7  #cbccc6

color8  #707a8c
color9  #ff6666
color10 #bae67e
color11 #ffcc66
color12 #5ccfe6
color13 #c3a6ff
color14 #95e6cb
color15 #ffffff
