background            #0a0e27
foreground            #d1f7ff
selection_foreground  #000000
selection_background  #00fff9

color0  #000000
color1  #ff2740
color2  #00ff9f
color3  #f9f002
color4  #00b8ff
color5  #bd00ff
color6  #00fff9
color7  #d1f7ff

color8  #4d4d4d
color9  #ff5577
color10 #55ffaf
color11 #ffff55
color12 #55c8ff
color13 #d955ff
color14 #55ffff
color15 #ffffff
