background            #000000
foreground            #e0e0e0
selection_foreground  #000000
selection_background  #e0e0e0

color0  #0a0a0a
color1  #808080
color2  #a0a0a0
color3  #c0c0c0
color4  #a0a0a0
color5  #909090
color6  #b0b0b0
color7  #e0e0e0

color8  #404040
color9  #a0a0a0
color10 #b8b8b8
color11 #d8d8d8
color12 #b8b8b8
color13 #a8a8a8
color14 #c8c8c8
color15 #ffffff
