background            #011627
foreground            #d6deeb
selection_foreground  #011627
selection_background  #82aaff

color0  #010e1a
color1  #ef5350
color2  #22da6e
color3  #ffeb95
color4  #82aaff
color5  #c792ea
color6  #7fdbca
color7  #d6deeb

color8  #575656
color9  #ef5350
color10 #22da6e
color11 #ffeb95
color12 #82aaff
color13 #c792ea
color14 #7fdbca
color15 #ffffff
