background            #292d3e
foreground            #a6accd
selection_foreground  #292d3e
selection_background  #82b1ff

color0  #1e2030
color1  #f07178
color2  #c3e88d
color3  #ffcb6b
color4  #82b1ff
color5  #c792ea
color6  #89ddff
color7  #a6accd

color8  #676e95
color9  #f07178
color10 #c3e88d
color11 #ffcb6b
color12 #82b1ff
color13 #c792ea
color14 #89ddff
color15 #ffffff
