background            #241b30
foreground            #f4e9d0
selection_foreground  #241b30
selection_background  #36f9f6

color0  #1a1428
color1  #fe4450
color2  #72f1b8
color3  #fede5d
color4  #03edf9
color5  #c792ea
color6  #36f9f6
color7  #f4e9d0

color8  #495495
color9  #ff6b7f
color10 #92ffd0
color11 #ffefaf
color12 #55f7ff
color13 #dda9ff
color14 #66ffff
color15 #ffffff
