bg = "#282a36"
bg_alt = "#21222c"
fg = "#f8f8f2"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
purple = "#ff79c6"
cyan = "#8be9fd"
accent = "#bd93f9"
dunst_bg = "#21222c"
dunst_fg = "#f8f8f2"
ok = "#50fa7b"
bg_crit = "#3d1e2c"
fg_crit = "#ffdada"
gtk_theme = "Sweet-Dark"
gtk_icon = "Papirus-Dark"
icon_color = "violet"
