bg = "#282c34"
bg_alt = "#1e222a"
fg = "#dcdfe4"
red = "#ff6c6b"
green = "#98be65"
yellow = "#ecbe7b"
blue = "#51afef"
purple = "#c678dd"
cyan = "#46d9ff"
accent = "#51afef"
dunst_bg = "#1c2028"
dunst_fg = "#bbc2cf"
ok = "#98be65"
bg_crit = "#2b1517"
fg_crit = "#ffdada"
gtk_theme = "Sweet-Dark"
gtk_icon = "Papirus-Dark"
icon_color = "blue"
