bg = "#000000"
bg_alt = "#0a0a0a"
fg = "#00ff41"
red = "#ff0000"
green = "#00ff41"
yellow = "#c0ff00"
blue = "#008f11"
purple = "#00b849"
cyan = "#00ff9f"
accent = "#00ff9f"
dunst_bg = "#000000"
dunst_fg = "#00ff41"
ok = "#00ff41"
bg_crit = "#1a0000"
fg_crit = "#ffdada"
gtk_theme = "Sweet-Dark"
gtk_icon = "Papirus-Dark"
icon_color = "green"
