description: Base system packages

packages:
  # Core system (documented intent)
  - base
  - base-devel
  # - linux
  # - linux-firmware
  # - intel-ucode
  # - efibootmgr
  # - zram-generator

  # Documentation & basics

  # dcli itself + its deps
  - dcli-arch-git
  - paru
  - yay
  - fzf
  - timeshift
  - timeshift-autosnap
  - pacman-contrib
  # speed / safety
  - zram-generator
  - earlyoom

exclude: []
conflicts:
  - linux-lts
  - linux-zen
  - linux-hardened
