bg = "#0a0e27"
bg_alt = "#000000"
fg = "#d1f7ff"
red = "#ff2740"
green = "#00ff9f"
yellow = "#f9f002"
blue = "#00b8ff"
purple = "#bd00ff"
cyan = "#00fff9"
accent = "#00fff9"
dunst_bg = "#0a0e27"
dunst_fg = "#d1f7ff"
ok = "#00ff9f"
bg_crit = "#3d1f2a"
fg_crit = "#ffdada"
gtk_theme = "Sweet-Dark"
gtk_icon = "Papirus-Dark"
icon_color = "pink"
