bg = "#f4f4f2"
bg_alt = "#e4e4e0"
fg = "#1c1c1c"
red = "#c00000"
green = "#006000"
yellow = "#805000"
blue = "#1a5fd0"
purple = "#600060"
cyan = "#005080"
accent = "#1a5fd0"
dunst_bg = "#f4f4f2"
dunst_fg = "#1c1c1c"
ok = "#006000"
bg_crit = "#ffd0d0"
fg_crit = "#600000"
gtk_theme = "Breeze"
gtk_icon = "Papirus-Light"
icon_color = "grey"
