bg = "#272822"
bg_alt = "#1e1f1c"
fg = "#f8f8f2"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
purple = "#ae81ff"
cyan = "#a1efe4"
accent = "#66d9ef"
dunst_bg = "#272822"
dunst_fg = "#f8f8f2"
ok = "#a6e22e"
bg_crit = "#3d1f2a"
fg_crit = "#ffdada"
gtk_theme = "Sweet-Dark"
gtk_icon = "Papirus-Dark"
icon_color = "yellow"
