bg = "#1f2430"
bg_alt = "#171b24"
fg = "#cbccc6"
red = "#ff6666"
green = "#bae67e"
yellow = "#ffcc66"
blue = "#5ccfe6"
purple = "#c3a6ff"
cyan = "#95e6cb"
accent = "#5ccfe6"
bg_crit = "#3d1f2a"
fg_crit = "#ffdada"
gtk_theme = "Sweet-Dark"
gtk_icon = "Papirus-Dark"
icon_color = "cyan"
