#!/usr/bin/env python3
"""Regenerate docs/assets/search-index.js from the pages next to it.

The manual has no build step -- the pages are hand-written HTML served
straight off GitHub Pages. This is the one exception, and it is committed
output: run it after editing a page, and commit both.

It indexes every h1/h2/h3 that has an id, plus the paragraph text that
follows, so the box in the header can match on body words as well as on
headings.
"""
import html
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent

PAGES = [
    ("index.html", "Home"),
    ("install-usb.html", "Install from the ATI-OS USB"),
    ("install-git.html", "Install from a git clone"),
    ("keybindings.html", "Keybindings"),
    ("themes.html", "The themes"),
    ("widgets.html", "Widgets and popups"),
    ("tools.html", "Everyday tools"),
    ("troubleshooting.html", "Troubleshooting"),
    ("reference.html", "Reference"),
]

TAG = re.compile(r"<[^>]+>")
HEADING = re.compile(
    r'<(h[123])(?:\s[^>]*?)?\sid="([^"]+)"[^>]*>(.*?)</\1>|<h1[^>]*>(.*?)</h1>',
    re.S,
)


def text(fragment: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(TAG.sub(" ", fragment))).strip()


def main() -> None:
    entries = []
    for filename, page in PAGES:
        raw = (HERE / filename).read_text(encoding="utf-8")
        body = raw.split("<main>", 1)[-1].split("</main>", 1)[0]

        marks = [(m.start(), m) for m in HEADING.finditer(body)]
        for i, (pos, m) in enumerate(marks):
            hid = m.group(2)
            title = text(m.group(3) or m.group(4) or "")
            if not title:
                continue
            end = marks[i + 1][0] if i + 1 < len(marks) else len(body)
            blurb = text(body[m.end():end])[:600]
            entries.append({
                "t": title,
                "p": page,
                "u": filename + ("#" + hid if hid else ""),
                "b": blurb,
            })

    out = (
        "/* Generated by docs/build-index.py -- do not edit by hand. */\n"
        "window.SEARCH_INDEX = "
        + json.dumps(entries, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    (HERE / "assets" / "search-index.js").write_text(out, encoding="utf-8")
    print(f"{len(entries)} entries -> assets/search-index.js")


if __name__ == "__main__":
    main()
