bg = "#2e3440"
bg_alt = "#3b4252"
fg = "#d8dee9"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
purple = "#b48ead"
cyan = "#88c0d0"
accent = "#88c0d0"
dunst_bg = "#2e3440"
dunst_fg = "#d8dee9"
ok = "#a3be8c"
bg_crit = "#3b1f22"
fg_crit = "#ffdada"
gtk_theme = "Sweet-Dark"
gtk_icon = "Papirus-Dark"
icon_color = "blue"
