bg = "#1f1f28"
bg_alt = "#16161d"
fg = "#dcd7ba"
red = "#e46876"
green = "#98bb6c"
yellow = "#e6c384"
blue = "#7e9cd8"
purple = "#957fb8"
cyan = "#7aa89f"
accent = "#7e9cd8"
dunst_bg = "#1f1f28"
dunst_fg = "#dcd7ba"
ok = "#98bb6c"
bg_crit = "#3d1f22"
fg_crit = "#ffdada"
gtk_theme = "Sweet-Dark"
gtk_icon = "Papirus-Dark"
icon_color = "blue"
